version: "3.10"
services:
  client:
    restart: always
    build:
      context: ./services/client
      target: production
    volumes:
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
      - ./services/client:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://server:8000
  server:
    restart: always
    build:
      context: ./services/api
      target: production
    volumes:
      - ./services/api:/usr/src/app
    ports:
      - "3001:8000"
