version: "3.10"
services:
  client:
    depends_on:
      - server
    restart: always
    build:
      context: ./services/client
      target: development
    volumes:
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
      - ./services/client:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://server:8000
    command: >
      bash -c "npm run generate:api && npm run dev"
  server:
    restart: always
    build:
      context: ./services/api
      target: development
    volumes:
      - ./services/api:/usr/src/app
    ports:
      - "3001:8000"
